### ISSUE TITLE
PyTorch source?

### ISSUE THREAD

**Issue by GeorgeS2019** [WindDYTING/DeepWind#1]
Hi Wu Tingyu, 您好

Could you please share any of the PyTorch module code?
This will help others to learn from you how your port that to TorchSharp :-)

**Comment by WindDYTING** [comment]
Hi @GeorgeS2019 I have put the pytorch source code link into DenseNet.cs and MobileNetV3.cs.

If you have any questions, welcome questions.

**Comment by GeorgeS2019** [comment]
https://github.com/pytorch/vision/blob/v0.13.1/torchvision/models/densenet.py

**Comment by GeorgeS2019** [comment]
@WindDYTING 

We recently discussed how to address the Torchvision IO and Processing for TorchSharp. Your example AND experience and possibly the challenges you encountered will be of value to the TorchSharp Community team

Please share that [here ](https://github.com/dotnet/TorchSharp/issues/763)
